####Init ver of config.yaml
hub:
  services:
    dask-gateway:
      display: false
  config:
    GenericOAuthenticator:
      client_id: "development"
      client_secret: ""
      oauth_callback_url: /hub/oauth_callback
      authorize_url: /auth/realms/master/protocol/openid-connect/auth
      token_url: /auth/realms/master/protocol/openid-connect/token
      userdata_url: /auth/realms/master/protocol/openid-connect/userinfo
      login_service: Keycloak 
      username_claim: preferred_username
      userdata_params:
        state: state
     # Allow all keycloak users
      allow_all: true
      admin_users:
        - nathan 
        - admin
      scope:
        - openid
    JupyterHub:
      authenticator_class: generic-oauth
    #DummyAuthenticator:
    #  password: "some_password"
proxy:
  service:
    type: "ClusterIP"

scheduling:
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 1

singleuser:
  image:
    name: nathanles/custom-conda
    tag: cpu-latest
    pullPolicy: IfNotPresent
  extraNodeAffinity:
    required:
      - matchExpressions:
          - key: "lke.linode.com/pool-id"
            operator: In
            values:
              - "915711"
  #cmd: null 
  #lifecycleHooks:
  #  postStart:
  #    exec:
  #      command: ["ln", "-s", "/shared", "~/shared"]
  ###########################################################Storage
  storage:
    dynamic:
      #type: dynamic
      #capacity: 10Gi
      #homeMountPath: /home/jovyan
      storageClass: linode-block-storage-retain
    extraVolumes:
      # Arbitrary key for identity & ordering
      - name: jupyterhub-shared
        persistentVolumeClaim:
          claimName: shared-storage 
    extraVolumeMounts:
      - name: jupyterhub-shared
        mountPath: /shared
  ###########################################################UI
  #defaultUrl: "/lab"
  ######################################################Single user resources
  memory:
    limit: 4G
    guarantee: 2G
  cpu:
    limit: 2
    guarantee: 1
  profileList:
    - display_name: "CPU Server"
      description: "Spawns a notebook server withOUT access to a GPU"
    - display_name: "1 GPU "
      description: "Spawns a notebook server with access to a GPU"
      kubespawner_override:
        tolerations:
          - key: "hub.jupyter.org/dedicated"
            operator: "Equal"
            value: "user"
            effect: "NoSchedule"
        #cpu_limit: 2
        #cpu_guarantee: 1
        #mem_limit: "4G"
        #mem_guarantee: "2G"
        #extra_resource_limits:
        #  nvidia.com/gpu: "1"
        #extra_resource_guarantees:
        #  nvidia.com/gpu: "1"
        image: nathanles/custom-conda:gpu-test
        pullPolicy: IfNotPresent
        node_affinity_required:
          - matchExpressions:
             - key: "lke.linode.com/pool-id"
               operator: In
               values:
               - "901402"
    - display_name: "Dask Enabled GPU Cluster"
      description: "Dask managed distrubted workloads"
      kubespawner_override:
        tolerations:
          - key: "hub.jupyter.org/dedicated"
            operator: "Equal"
            value: "user"
            effect: "NoSchedule"
        cpu_limit: 8
        cpu_guarantee: 4
        mem_limit: "32G"
        mem_guarantee: "16G"
        #extra_resource_limits:
        #  nvidia.com/gpu: "2"
        #extra_resource_guarantees:
        #  nvidia.com/gpu: "2"
        #image: ghcr.io/dask/dask-notebook:2026.6.0
        image: nathanles/custom-conda:newer-dask
        #image: rapidsai/notebooks:26.06-cuda13-py3.13 
        pullPolicy: IfNotPresent 
        node_affinity_required:
          - matchExpressions:
             - key: "lke.linode.com/pool-id"
               operator: In
               values:
               - "913893"
