command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-port=8080"
  - "--hostname-strict=false"
  - "--proxy-headers=xforwarded"
extraEnv: |
  - name: KC_LOG_LEVEL
    value: ERROR 
  - name: KC_HOSTNAME
    value: <kc.domain.com> 
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: 
  - name: KC_DB 
    value: postgres
  - name: KC_DB_URL_HOST
    value: 
  - name: KC_DB_URL_PORT
    value: 
  - name: KC_DB_URL_DATABASE 
    value:  
  - name: KC_DB_USERNAME 
    value: 
  - name: KC_DB_PASSWORD
    value:  
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
#  affinity: |
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        -  matchExpressions:
#           - key: "lke.linode.com/pool-id"
#             operator: In
#             values:
#             - "845636"
