apiVersion: v1
kind: Service
metadata:
  name: {{ include "dask.fullname" . }}
  labels:
    {{- include "dask.labels" . | nindent 4 }}
spec:
  type: {{ .Values.traefik.service.type }}
  ports:
    - port: {{ .Values.traefik.service.ports.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dask.selectorLabels" . | nindent 4 }}
