apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-storage 
  namespace: dev-ai 
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 75Gi
  storageClassName: nfs 
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 75Gi
